<?php 
  $helper = $this->helper('AHT\Attribute\Helper\Data');
  $values = $helper->getAllOptions();
?>
<div class="field phone_add required">
    <label class="label" for="phone_add">
      <span><?= $block->escapeHtml(__('Phone')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="phone_add" id="phone_add" value="" title="<?= $block->escapeHtmlAttr(__('Phone')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>

<div class="field company_type required">
    <label class="label" for="company_type">
      <span><?= $block->escapeHtml(__('Company Type')) ?></span>
    </label>
    <!-- Day la cai select -->
    <select type="text" name="company_type" id="company_type" value=""  title="<?= $block->escapeHtmlAttr(__('Company Type')) ?>" class="input-text" data-validate="{required:true}">
      <?php foreach($values as $key => $value){ ?>
                <option id="<?php $value['value'];?>"><?php echo $value['value'];?></option> 
      <?php } ?>
    </select>
</div>
    <!-- Div minh muon hien ra -->
<div class="field organization_customer required" id="organization" style="display: none">
    <label class="label" for="organization_customer">
      <span><?= $block->escapeHtml(__('Organization Name')) ?></span>
    </label>
    <div class="control" >
      <input type="text"  name="organization_customer" id="organization_customer" value="" title="<?= $block->escapeHtmlAttr(__('Organization Name')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>
<script>
    require(['jquery', 'jquery/ui'], function($){
      $('#company_type').change(function() {
          if ($(this).val() === 'Other') {
            $("#organization").css("display","block")
          }else {
            $("#organization").css("display","none")
          }
      });
    });
</script>
